### ISSUE TITLE
求项目的前端

### ISSUE THREAD

**Issue by lingyi-743** [1145141919810ho/-#1]
兄弟啊，你的vue前端呢，求一个

**Comment by Spwek** [comment]
> 兄弟啊，你的vue前端呢，求一个

**Comment by Spwek** [comment]
抱歉没有前端，这只是个demo并不是完整的项目。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Spwek/Online-Course-Selection-System"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月6日(星期三) 晚上8:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Spwek/Online-Course-Selection-System] 求项目的前端 (#1)





 
兄弟啊，你的vue前端呢，求一个
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
